### ISSUE TITLE
Should jQuery References be reduced?

### ISSUE THREAD

**Issue by orangewolf** [sandiegojs/vanilla-browser-docs#19]
Hi,
 I noticed during review that the manipulation page talks a lot about how you might do these things in jQuery.  I think that is an unnecessary and possibly confusing to this audience. I didn't want to strip them out in case they were there intentionally or as a lesson learned.  Thoughts?

**Comment by hbrysiewicz** [comment]
Hmm... maybe so, I guess originally the point was to demonstrate how to do jQuery stuff without jQuery but its kind of become its own workshop outside of that topic now. Maybe it would be useful to remove the references...

**Comment by michaelerobertsjr** [comment]
:+1: to remove, kiss
