### ISSUE TITLE
Should "public/" references show "app/" instead?

### ISSUE THREAD

**Issue by treyhunner** [sandiegojs/vanilla-browser-docs#22]
I see both `public` directory references as well as `public/index.css` and similar references.

There is an `app` directory and there are `index.js` and `index.css` files.

It seems like `public` is generated for us. Is that the case? Should we leave `public` alone or are we supposed to actually change the files in `public`?

I think we at least need to note that there's both a `public` and `app` directory and very briefly note why we're changing one and not the other.

**Comment by hbrysiewicz** [comment]
Yes, public is generated. Originally, index.html in public was _not_ generated, but as it is now this should be updated. Good catch

**Comment by hbrysiewicz** [comment]
Fixed!
